/**
 * @file webhook.js
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status            = require('@converseai/plugins-sdk').Status;
const ExternalResponse  = require('@converseai/plugins-sdk').Payloads.ExternalFunctionResponse;

module.exports = function webhook (app, body) {
 /**
  * Registration parameters assigned to body.payload.registrationData
  * @example
  * var regOne = body.payload.registrationData.regOne;
  */

  /** @type {ExternalFunctionResponse} response The Converse AI response to respond with. */
  var response = new ExternalResponse();

  /*
  * This will return a success status and response to the conversation.
  * It is important to always call this method when the module has finished
  * otherwise the external call will timeout.
  */
  app.send(Status.SUCCESS, response);
};
