/**
 * @file list_users.js
 * @description List Users  
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status          = require('@converseai/plugins-sdk').Status;
const ModuleResponse  = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;
const request         = require('request-promise');

module.exports = function list_users (app, body) {
  const { token, orgId } = body.payload.registrationData;

  if (token != undefined && orgId != undefined) { 
    /** @type {ModuleResponse} response The Converse AI response to respond with. */
    const response = new ModuleResponse();

    const options = {
      url:`https://brandfolder.com/api/v4/organizations/${orgId}`,
      headers:{
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      json: true
    };

    request.get(options).then(result => {
      response.setValue(result);
      app.send(Status.SUCCESS, response);
        }).catch(err => {
          console.error(err)
          app.fail({ httpStatus: err.statusCode, error: err.error.errors }); 
        });
    
  } else { 
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameters are undefined.' }); 
  }
};
